API_CONFIG: 
  BSV_INFO:
    NETWORK: "test"
    CHUNK_SIZE_BYTES: 60000
  AZURE_INFO:
    ACCOUNT_NAME: ""
    ACCOUNT_KEY: ""
    UPLOAD_CONTAINER_NAME: "uploadcontainer"
    CHUNK_SIZE_BYTES: 100000
